// frontend-vue-ts/src/views/dashboard/users/Edit.vue
<script setup lang="ts">
import { ref, reactive, watch } from "vue";
import { useRouter, useRoute } from "vue-router";
import { type AxiosError } from "axios";
import { toast } from "vue-sonner";
import { useUserById } from "../../../composables/user/useUserById";
import { useUserUpdate } from "../../../composables/user/useUserUpdate";
import { type ValidationErrors } from "../../../types/common";
import { type UserResponse } from "../../../types/user";
import DashboardLayout from "../../../layouts/DashboardLayout.vue";
import useDocumentTitle from "../../../composables/common/useDocumentTitle";

useDocumentTitle("Edit User");

const route = useRoute();
const router = useRouter();

const id = route.params.id as string;
const { data: user } = useUserById(id);

const { mutate, isPending } = useUserUpdate();

const name = ref<string>("");
const email = ref<string>("");
const password = ref<string>("");
const errors = reactive<ValidationErrors>({});

watch(
  user,
  (newUser) => {
    if (newUser) {
      name.value = newUser.name;
      email.value = newUser.email;
    }
  },
  { immediate: true },
);

const handleUpdate = () => {
  mutate(
    {
      id,
      payload: {
        name: name.value,
        email: email.value,
        password: password.value,
      },
    },
    {
      onSuccess: (data: UserResponse) => {
        toast.success(data?.message || "User updated successfully");
        router.push({ name: "users" });
      },
      onError: (error: Error) => {
        const axiosError = error as AxiosError<{
          errors: Record<string, string>;
        }>;
        const validationErrors = axiosError.response?.data?.errors;
        if (validationErrors) {
          Object.assign(errors, validationErrors);
        } else {
          toast.error("Something went wrong");
        }
      },
    },
  );
};
</script>

<template>
  <DashboardLayout>
    <div class="card border-0 rounded-4 shadow-sm">
      <div class="card-header">EDIT USER</div>
      <div class="card-body">
        <p v-if="!user">Loading...</p>

        <form v-else @submit.prevent="handleUpdate">

          <div class="form-group mb-3">
            <label class="mb-1 fw-bold">Full Name</label>
            <input
              v-model="name"
              type="text"
              :class="`form-control ${errors.name ? 'is-invalid' : ''}`"
              placeholder="Full Name"
            />
            <div v-if="errors.name" class="invalid-feedback">
              {{ errors.name }}
            </div>
          </div>

          <div class="form-group mb-3">
            <label class="mb-1 fw-bold">Email Address</label>
            <input
              v-model="email"
              type="email"
              :class="`form-control ${errors.email ? 'is-invalid' : ''}`"
              placeholder="Email Address"
            />
            <div v-if="errors.email" class="invalid-feedback">
              {{ errors.email }}
            </div>
          </div>

          <div class="form-group mb-3">
            <label class="mb-1 fw-bold">Password</label>
            <input
              v-model="password"
              type="password"
              :class="`form-control ${errors.password ? 'is-invalid' : ''}`"
              placeholder="Leave blank to keep current password"
            />
            <div v-if="errors.password" class="invalid-feedback">
              {{ errors.password }}
            </div>
          </div>

          <button
            type="submit"
            class="btn btn-md btn-primary rounded-4 shadow-sm border-0"
            :disabled="isPending"
          >
            {{ isPending ? "Updating..." : "Update" }}
          </button>

          <RouterLink
            to="/dashboard/users"
            class="btn btn-md btn-secondary rounded-4 shadow-sm border-0 ms-2"
          >
            Cancel
          </RouterLink>

        </form>
      
      </div>
    </div>
  </DashboardLayout>
</template>

// examples/frontend-bootstrap/frontend-react-ts/src/views/dashboard/users/Edit.tsx
import { type FC, useState, type FormEvent } from "react";
import { useNavigate, useParams, Link } from "react-router";
import { type AxiosError } from "axios";
import toast from "react-hot-toast";
import { useUserById } from "../../../hooks/user/useUserById";
import { useUserUpdate } from "../../../hooks/user/useUserUpdate";
import { type ValidationErrors } from "../../../types/common";
import { type UserResponse, type User } from "../../../types/user";
import useDocumentTitle from "../../../hooks/common/useDocumentTitle";
import DashboardLayout from "../../../layouts/DashboardLayout";

const UserEditForm: FC<{ user: User }> = ({ user }) => {
  useDocumentTitle("Edit User");

  const navigate = useNavigate();
  const { mutate, isPending } = useUserUpdate();

  const [name, setName] = useState<string>(user.name);
  const [email, setEmail] = useState<string>(user.email);
  const [password, setPassword] = useState<string>("");
  const [errors, setErrors] = useState<ValidationErrors>({});

  const handleUpdate = async (e: FormEvent) => {
    e.preventDefault();

    mutate(
      {
        id: user.id,
        payload: { name, email, password },
      },
      {
        onSuccess: (data: UserResponse) => {
          toast.success(data?.message || "User updated successfully");
          navigate("/dashboard/users");
        },
        onError: (error: Error) => {
          const axiosError = error as AxiosError<{
            errors: Record<string, string>;
          }>;
          const validationErrors = axiosError.response?.data?.errors;
          if (validationErrors) {
            setErrors(validationErrors);
          } else {
            toast.error("Something went wrong");
          }
        },
      },
    );
  };

  return (
    <form onSubmit={handleUpdate}>
      <div className="form-group mb-3">
        <label className="mb-1 fw-bold">Full Name</label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          className={`form-control ${errors.name ? "is-invalid" : ""}`}
          placeholder="Full Name"
        />
        {errors.name && <div className="invalid-feedback">{errors.name}</div>}
      </div>

      <div className="form-group mb-3">
        <label className="mb-1 fw-bold">Email Address</label>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={`form-control ${errors.email ? "is-invalid" : ""}`}
          placeholder="Email Address"
        />
        {errors.email && <div className="invalid-feedback">{errors.email}</div>}
      </div>

      <div className="form-group mb-3">
        <label className="mb-1 fw-bold">Password</label>
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className={`form-control ${errors.password ? "is-invalid" : ""}`}
          placeholder="Leave blank to keep current password"
        />
        {errors.password && (
          <div className="invalid-feedback">{errors.password}</div>
        )}
      </div>

      <button
        type="submit"
        className="btn btn-md btn-primary rounded-4 shadow-sm border-0"
        disabled={isPending}
      >
        {isPending ? "Updating..." : "Update"}
      </button>

      <Link
        to="/dashboard/users"
        className="btn btn-md btn-secondary rounded-4 shadow-sm border-0 ms-2"
      >
        Cancel
      </Link>
    </form>
  );
};

const UserEdit: FC = () => {
  useDocumentTitle("Edit");

  const { id } = useParams();
  const { data: user } = useUserById(String(id));

  return (
    <DashboardLayout>
      <div className="card border-0 rounded-4 shadow-sm">
        <div className="card-header">EDIT USER</div>
        <div className="card-body">
          {user ? <UserEditForm user={user} /> : <p>Loading...</p>}
        </div>
      </div>
    </DashboardLayout>
  );
};

export default UserEdit;
