// frontend-react-ts/src/views/dashboard/users/Index.tsx
import { type FC } from "react";
import { Link } from "react-router";
import { useQueryClient } from "@tanstack/react-query";
import { useUsers } from "../../../hooks/user/useUsers";
import { useUserDelete } from "../../../hooks/user/useUserDelete";
import { type User } from "../../../types/user";
import DashboardLayout from "../../../layouts/DashboardLayout";
import useDocumentTitle from "../../../hooks/common/useDocumentTitle";

const UsersIndex: FC = () => {
  useDocumentTitle("Users");

  const { data: users, isLoading, isError, error } = useUsers();

  const queryClient = useQueryClient();

  const { mutate, isPending } = useUserDelete();

  const handleDelete = (id: string) => {
    if (confirm("Are you sure you want to delete this user?")) {
      mutate(id, {
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: ["users"] });
        },
      });
    }
  };

  return (
    <DashboardLayout>
      <div className="card border-0 rounded-4 shadow-sm">
        <div className="card-header d-flex justify-content-between align-items-center">
          <span>USERS</span>
          <Link
            to="/dashboard/users/create"
            className="btn btn-sm btn-success rounded-4 shadow-sm border-0"
          >
            ADD USER
          </Link>
        </div>
        <div className="card-body">
          {/* Loading State */}
          {isLoading && (
            <div className="alert alert-info text-center">Loading...</div>
          )}

          {/* Error State */}
          {isError && (
            <div className="alert alert-danger text-center">
              Error: {error.message}
            </div>
          )}

          <div className="table-responsive">
            <table className="table table-bordered">
              <thead className="bg-dark text-white">
                <tr>
                  <th scope="col">Full Name</th>
                  <th scope="col">Email Address</th>
                  <th scope="col" style={{ width: "20%" }}>
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                {users?.map((user: User) => (
                  <tr key={user.id}>
                    <td>{user.name}</td>
                    <td>{user.email}</td>
                    <td className="text-center">
                      <Link
                        to={`/dashboard/users/edit/${user.id}`}
                        className="btn btn-sm btn-primary rounded-4 shadow-sm border-0 me-2"
                      >
                        EDIT
                      </Link>

                      <button
                        onClick={() => handleDelete(user.id)}
                        disabled={isPending}
                        className="btn btn-sm btn-danger rounded-4 shadow-sm border-0"
                      >
                        {isPending ? "DELETING..." : "DELETE"}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default UsersIndex;

// frontend-vue-ts/src/views/dashboard/users/Index.vue
<script setup lang="ts">
import { useQueryClient } from "@tanstack/vue-query";
import { useUsers } from "../../../composables/user/useUsers";
import { useUserDelete } from "../../../composables/user/useUserDelete";
import { type User } from "../../../types/user";
import DashboardLayout from "../../../layouts/DashboardLayout.vue";
import useDocumentTitle from "../../../composables/common/useDocumentTitle";

useDocumentTitle("Users");

const { data: users, isLoading, isError, error } = useUsers();
const queryClient = useQueryClient();
const { mutate, isPending } = useUserDelete();

const handleDelete = (id: string) => {
  if (confirm("Are you sure you want to delete this user?")) {
    mutate(id, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ["users"] });
      },
    });
  }
};
</script>

<template>
  <DashboardLayout>
    <div class="card border-0 rounded-4 shadow-sm">
      <div
        class="card-header d-flex justify-content-between align-items-center"
      >
        <span>USERS</span>
        <RouterLink
          to="/dashboard/users/create"
          class="btn btn-sm btn-success rounded-4 shadow-sm border-0"
        >
          ADD USER
        </RouterLink>
      </div>
      <div class="card-body">
        <div v-if="isLoading" class="alert alert-info text-center">
          Loading...
        </div>

        <div v-if="isError" class="alert alert-danger text-center">
          Error: {{ error?.message }}
        </div>

        <div class="table-responsive">
          <table class="table table-bordered">
            <thead class="bg-dark text-white">
              <tr>
                <th scope="col">Full Name</th>
                <th scope="col">Email Address</th>
                <th scope="col" style="width: 20%">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="user in users as User[]" :key="user.id">
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td class="text-center">
                  <RouterLink
                    :to="`/dashboard/users/edit/${user.id}`"
                    class="btn btn-sm btn-primary rounded-4 shadow-sm border-0 me-2"
                  >
                    EDIT
                  </RouterLink>
                  <button
                    @click="handleDelete(user.id)"
                    :disabled="isPending"
                    class="btn btn-sm btn-danger rounded-4 shadow-sm border-0"
                  >
                    {{ isPending ? "DELETING..." : "DELETE" }}
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </DashboardLayout>
</template>
