// frontend-react-ts/src/views/dashboard/Index.tsx
import { type FC } from "react";
import { useAuthStore } from "../../stores/auth";
import DashboardLayout from "../../layouts/DashboardLayout";
import useDocumentTitle from "../../hooks/common/useDocumentTitle";

const Dashboard: FC = () => {
  useDocumentTitle("Dashboard");

  const { user } = useAuthStore();

  return (
    <DashboardLayout>
      <div className="card border-0 rounded-4 shadow-sm">
        <div className="card-header">DASHBOARD</div>
        <div className="card-body">
          Selamat Datang, <strong>{ user?.name || "" }</strong>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default Dashboard;

// frontend-vue-ts/src/views/dashboard/Index.vue
<script setup lang="ts">
import { useAuthStore } from "../../stores/auth";
import DashboardLayout from "../../layouts/DashboardLayout.vue";
import useDocumentTitle from "../../composables/common/useDocumentTitle";

useDocumentTitle("Dashboard");

const authStore = useAuthStore();
</script>

<template>
  <DashboardLayout>
    <div class="card border-0 rounded-4 shadow-sm">
      <div class="card-header">DASHBOARD</div>
      <div class="card-body">
        Selamat Datang, <strong>{{ authStore.user?.name || "" }}</strong>
      </div>
    </div>
  </DashboardLayout>
</template>
