// frontend-vue-ts/src/components/dashboard/NavBar.vue
<script setup lang="ts">
import { APP_NAME } from "../../constants/app";

const props = withDefaults(
  defineProps<{
    userEmail?: string;
    onSignOut?: () => void;
  }>(),
  {
    userEmail: "User",
  },
);
</script>

<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3 shadow-sm">
    <RouterLink class="navbar-brand fw-bold fs-5" to="/dashboard">
      ⚡ {{ APP_NAME }}
    </RouterLink>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon" />
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-light"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            👤 {{ props.userEmail }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <RouterLink class="dropdown-item" to="/dashboard/profile">
                My Profile
              </RouterLink>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <button
                class="dropdown-item text-danger"
                @click="props.onSignOut?.()"
              >
                Sign Out
              </button>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</template>

// frontend-react-ts/src/components/dashboard/NavBar.tsx
import type { FC } from "react";
import { Link } from "react-router";
import { APP_NAME } from "../../constants/app";

type NavBarProps = {
  userEmail?: string;
  onSignOut?: () => void;
};

const NavBar: FC<NavBarProps> = ({ userEmail = "John Doe", onSignOut }) => (
  <nav className="navbar navbar-expand-lg navbar-dark bg-dark px-3 shadow-sm">
    <Link className="navbar-brand fw-bold fs-5" to="/dashboard">
      ⚡ { APP_NAME }
    </Link>

    <button
      className="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span className="navbar-toggler-icon" />
    </button>

    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav ms-auto">
        {" "}
        <li className="nav-item dropdown">
          <a
            className="nav-link dropdown-toggle text-light"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            👤 {userEmail}
          </a>
          <ul className="dropdown-menu dropdown-menu-end">
            {" "}
            <li>
              <Link className="dropdown-item" to="/dashboard/profile">
                My Profile
              </Link>
            </li>
            <li>
              <hr className="dropdown-divider" />
            </li>
            <li>
              <button className="dropdown-item text-danger" onClick={onSignOut}>
                Sign Out
              </button>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
);

export default NavBar;
