// frontend-vue-ts/src/components/dashboard/SideBar.vue
<script setup lang="ts"></script>

<template>
  <div class="card border-0 rounded-4 shadow-sm">
    <div class="card-header">MAIN MENU</div>
    <div class="card-body">
      <div class="list-group">
        <RouterLink
          to="/dashboard"
          class="list-group-item list-group-item-action"
        >
          Dashboard
        </RouterLink>

        <RouterLink
          to="/dashboard/users"
          class="list-group-item list-group-item-action"
        >
          Users
        </RouterLink>
      </div>
    </div>
  </div>
</template>

// frontend-react-ts/src/components/dashboard/SideBar.tsx
import type { FC } from "react";
import { Link } from "react-router";

const SideBar: FC = () => {
  return (
    <div className="card border-0 rounded-4 shadow-sm">
      <div className="card-header">MAIN MENU</div>
      <div className="card-body">
        <div className="list-group">
          <Link
            to="/dashboard"
            className="list-group-item list-group-item-action"
          >
            Dashboard
          </Link>

          <Link
            to="/dashboard/users"
            className="list-group-item list-group-item-action"
          >
            Users
          </Link>
        </div>
      </div>
    </div>
  );
};

export default SideBar;
