// frontend-vue-ts/src/components/dashboard/SideBar.vue
<script setup lang="ts"></script>

<template>
  <div class="card border-0 rounded-4 shadow-sm">
    <div class="card-header">MAIN MENU</div>
    <div class="card-body">
      <div class="list-group">
        <RouterLink
          to="/dashboard"
          class="list-group-item list-group-item-action"
          exact-active-class="active"
        >
          Dashboard
        </RouterLink>

        <RouterLink
          to="/dashboard/users"
          class="list-group-item list-group-item-action"
          active-class="active"
        >
          Users
        </RouterLink>
      </div>
    </div>
  </div>
</template>

// examples/frontend-bootstrap/frontend-react-ts/src/components/dashboard/SideBar.tsx
import type { FC } from "react";
import { NavLink } from "react-router";

const SideBar: FC = () => {
  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `list-group-item list-group-item-action${isActive ? " active" : ""}`;

  return (
    <div className="card border-0 rounded-4 shadow-sm">
      <div className="card-header">MAIN MENU</div>

      <div className="card-body">
        <div className="list-group">
          <NavLink to="/dashboard" end className={navLinkClass}>
            Dashboard
          </NavLink>

          <NavLink to="/dashboard/users" className={navLinkClass}>
            Users
          </NavLink>
        </div>
      </div>
    </div>
  );
};

export default SideBar;
